### ISSUE TITLE
Wrong triggered bits in the shared memory `fish_map`

### ISSUE THREAD

**Issue by JJLeo** [HexHive/FishFuzz#6]
Dear authors,

I noticed that there are wrong triggered bits in the shared memory `fish_map` when I used the [crashed seeds](https://github.com/user-attachments/files/17977833/crashes.tar.gz) to test the ASAN program `gif2tga`. There are only 382 targets in `git2tga` but there are many triggered bits whose index is greater than 382:

```
{"ffapp": {"1322": [241], "11972": [291], "12159": [379], "
12282": [279], "61927": [241], "194146": [291], "195206": [379], "195302": [379], "658969": [279], "755286": [279, 299], "815876": [379], "834456": [279], "846573": [379], "873921": [379], "884527": [302], "1125912": [379], "1680768": [291], "2011310": [379], "2073432": [280], "4692290": [278], "5653626": [299, 379], "10201750": [302], "12408505": [299, 2561, 2563, 2565, 2567, 2569, 2571, 2577, 2579, 2581, 2583, 2585, 2587, 2593, 2595, 2597, 2599, 2601, 2603, 2609, 2611, 2613, 2615, 2617, 2619, 2625, 2627, 2629, 2631, 2633, 2635, 2641, 2643, 2645, 2647, 2649, 2651, 2657, 2659, 2661, 2663, 2665, 2667, 2673, 2675, 2677, 2679, 2681, 2683, 2689, 2691, 2693, 2695, 2697, 2699, 2705, 2707, 2709, 2711, 2713, 2715, 2721, 2723, 2725, 2727, 2729, 2731, 2737, 2739, 2741, 2743, 2745, 2747, 2753, 2755, 2757, 2759, 2761, 2763, 2769, 2771, 2773, 2775, 2777, 2779, 2785, 2787, 2789, 2791, 2793, 2795, 2801, 2803, 2805, 2807, 2809, 2811, 2817, 2819, 2821, 2823, 2825, 2827, 2833, 2835, 2837, 2839, 2841, 2843, 2849, 2851, 2853, 2855, 2857, 2859, 2865, 2867, 2869, 2871, 2873, 2875, 2881, 2883, 2885, 2887, 2889, 2891, 2897, 2899, 2901, 2903, 2905, 2907, 2913, 2915, 2917, 2919, 2921, 2923, 2929, 2931, 2933, 2935, 2937, 2939, 2945, 2947, 2949, 2951, 2953, 2955, 2961, 2963,
...
```

I suspect that the shared memory is being accessed incorrectly by the program.

Thanks!

**Comment by kdsjZh** [comment]
Hi,

As discussed in the email, this issue is not FishFuzz-specific. i.e. AFL instrumented binary also encountered these OOB share memory write. So it seems to be a benchmark issue. 

Therefore, it's recommended not to use the gif2tga for evaluation, and this issue does not affect the FishFuzz performance. 

BTW, we have a [TuneFuzz](https://github.com/HexHive/FishFuzz/tree/tunefuzz_sbft24) extension, which has better performance and does not rely on LTO. If your goal is not to reproduce the results/compare, it's recommended to play with TuneFuzz.

Based on our email discussion, I assume this issue is resolved, If you have further questions, feel free to reopen.

Cheers,
Han
